# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official lightweight Node.js image
FROM node:20-alpine AS base

# Set working directory
WORKDIR /app

# Copy pnpm-lock.yaml and .npmrc (if exists)
COPY pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and tsconfig.json
COPY examples/simple-server/package.json examples/simple-server/tsconfig.json ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the source files
COPY examples/simple-server/index.ts ./

# Use tsx to run the server
CMD ["pnpm", "run", "start"]
