# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official lightweight Node.js image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and tsconfig.json
COPY examples/simple-server/package.json examples/simple-server/tsconfig.json ./

# Install the dependencies
RUN npm install

# Copy the application code
COPY examples/simple-server .

# Expose the application port
EXPOSE 9512

# Command to run the application
CMD ["npm", "run", "start"]